#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
 
use Symfony\Component\Console\Application;
use Console\TimeCommand;
use Console\TellCommand;
use Console\DailyQuestion;
use Console\Login;
use Console\Aggregate;
use Console\Add;
use Console\Subtract;

 
$app = new Application('Sindy', 'v1.0.0');
$app ->add(new TimeCommand());
$app ->add(new TellCommand());
$app ->add(new DailyQuestion());
$app ->add(new Login());
$app ->add(new Aggregate());
$app ->add(new Add());
$app ->add(new Subtract());
$app->run();
